<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <NoWarn>xUnit2013;CS9113</NoWarn>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableFastUpToDateCheck>True</DisableFastUpToDateCheck>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="TestData\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <PropertyGroup Condition="$(MSBuildProjectName) == 'MixedIL.Tests'">
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --report-trx</TestingPlatformCommandLineArguments>
  </PropertyGroup>
</Project>
