<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--This project must target netstandard2.0.-->
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <PackageId>$(MSBuildProjectName).Fody</PackageId>
    <RootNamespace></RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <!-- Use Nullable instead of PolySharp to avoid bringing ValueTuple into the project that uses this package. -->
    <PackageReference Include="Nullable" PrivateAssets="all" />
    <PackageReference Include="MoreFodyHelpers" GeneratePathProperty="true" />
  </ItemGroup>
</Project>