<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;</TargetFrameworks>
    <DisableFastUpToDateCheck>True</DisableFastUpToDateCheck>
    <PublishAot>true</PublishAot>
    <IsPackable>false</IsPackable>
    <RootNamespace></RootNamespace>
    <!--<DisableFody>true</DisableFody>-->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Fody" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MixedIL.Fody\MixedIL.Fody.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\MixedIL\MixedIL.csproj" PrivateAssets="all" />
  </ItemGroup>  
  <Import Project="..\LocalWeaver.props" />
  <Import Project="..\LocalInclude.props" />
  <ItemGroup>
    <Compile Include="System\ObjectExtensions.fs" />
    <Compile Include="System\ObjectHelper.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\MixedIL.Example\System\*.il;" Link="System\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
